### ISSUE TITLE
Deal start condition missing.

### ISSUE THREAD

**Issue by Mkopl360** [MarcDrexler/3Commas.BulkEditor#1]
i have keiko_futures deal start condition in 3commas but its missing in the bot. for both create and edit

**Comment by Mkopl360** [comment]
also i notice only long bot is display. short are missing.
btw thanks for the editor its help a lot

**Comment by Mkopl360** [comment]
also on create bot , Leverage missing

**Comment by Grepsy** [comment]
I've implemented this in https://github.com/MarcDrexler/3Commas.BulkEditor/pull/2.

**Comment by MarcDrexler** [comment]
I've broken up this issue into several small ones and will close this one.
