### ISSUE TITLE
Missing column and copied bots don't start

### ISSUE THREAD

**Issue by Trivo2311** [MarcDrexler/3Commas.BulkEditor#11]
When i copied bots to a new 3commas account DCA bot's dont run until i edit each one as they are in gordon bots and i have to select advanced and save them individually to get them to work

**Comment by MarcDrexler** [comment]
I fixed the problem. New bots are now also enabled if the bot to be copied was enabled.

Regarding the website problem, there is unfortunately not much I can do.
3c Support told me: 
"_We stored from what tab bot was created/edited. When it was created from the API - default tab is used_"

**Comment by Trivo2311** [comment]
Thanks any chance of getting a tab for the bot pair. When I made the bots all the name descriptions are eg: binance001 long. And does not have the pair name so I don’t know which bot is which.
Thanks grant

**Comment by MarcDrexler** [comment]
When bulk editing your bot names, you can use placeholders like {{strategy}} and/or {{pair}}.

For example:
**My {{strategy}} {{pair}} Bot**
will result in: 
**My Long USDT_BTC Bot**

**Comment by Trivo2311** [comment]
Yes I understand that but tab “bot id” it has a bot number which cant be found on 3commas, cant you put another one with “Bot pair“

**Comment by MarcDrexler** [comment]
Ok now I got it. So you mean a column in the table for the pair?
I will add it soon.

**Comment by Trivo2311** [comment]
Thanks that will be really helpful

**Comment by Trivo2311** [comment]
Just opened Bulk Builder it is perfect 
Thanks for your effort
Grant
