### ISSUE TITLE
Can you add strategy ?

### ISSUE THREAD

**Issue by Missgoodluck** [MarcDrexler/3Commas.BulkEditor#13]
Hi , the bulkapp working good, but mine copy and upload only Long bots , i cant change strategy (in function Edit), is there is way to upload and copy both types of bots and short and long ?

**Comment by Missgoodluck** [comment]
Here the printscreen its not even have it (http://joxi.ru/MAjqKYbSk1yoD2))

**Comment by MarcDrexler** [comment]
There is no limitation for Long Bots only. You should see both, Long and Short:
![image](https://user-images.githubusercontent.com/16029585/98175335-ac833480-1ef6-11eb-8e04-88d67d35e091.png)



Available filter options are always reduced to the current view. Maybe you have already set another filter which hides all of your short bots, therefore the filter option for Short is not needed and not shown.

If you click on this icon, current filters will be reset and your Short Bots should appear:
![image](https://user-images.githubusercontent.com/16029585/98175110-45fe1680-1ef6-11eb-8c67-0764b6d4ff23.png)

**Comment by Missgoodluck** [comment]
I did it:( and if you take a look on my printscreen it’s still loaded only Long bots. May be you use other version ? 

Sincerely Kristina .

**Comment by Missgoodluck** [comment]
P/s  its not even loading in strategy [](http://joxi.ru/12M6MGZikwJQEA) (((may be you can take a look hy only one type of Strategy loading

**Comment by Missgoodluck** [comment]
http://joxi.ru/12M6MGZikwJQEA

**Comment by MarcDrexler** [comment]
Is 499 the total count of your bots including shorts or are they missing in this number?

I'm asking this to find out if it's a problem getting the bots or just a problem in the UI.

**Comment by Missgoodluck** [comment]
No they missing , you now I see what happened , the app upload short bots only if they able, when they disabled (in my case I switch all bots long and short off to make settings), app upload only long bots. 
So to upload short ones need activated them 🤷🏻‍♀️

**Comment by Missgoodluck** [comment]
))thank you its fixed
