### ISSUE TITLE
strategy

### ISSUE THREAD

**Issue by Trivo2311** [MarcDrexler/3Commas.BulkEditor#14]
Hi Marc any chance of adding a strategy button to the edit window
![image](https://user-images.githubusercontent.com/49354890/98324179-8c529300-2026-11eb-9b91-106bf908bd65.png)
![strategy](https://user-images.githubusercontent.com/49354890/98324208-9ecccc80-2026-11eb-94ec-62cf61f25d42.PNG)

ow

**Comment by MarcDrexler** [comment]
Yes, that should be possible... at least the 3commas API seems to allow that. But be aware to change other necessary fields to match the new strategy. 😅 For example, the order volume may need to be adjusted.

**Comment by Trivo2311** [comment]
Ok thanks Marc

**Comment by MarcDrexler** [comment]
Unfortunately I have to correct myself. It is not possible to change the strategy of an existing bot via the API.
I just received an answer from 3c support about this.

**Comment by Trivo2311** [comment]
Ok well worth a try
Thanks for everything
