### ISSUE TITLE
error on installation 

### ISSUE THREAD

**Issue by Crypto-2018** [MarcDrexler/3Commas.BulkEditor#16]
Hi there, I can't run the software, can you please help 

Thanks
![error](https://user-images.githubusercontent.com/36448360/98826003-89331a80-240b-11eb-87b8-fc4a20799895.PNG)

**Comment by MarcDrexler** [comment]
Hi, thanks for reporting this one.

I've released a new version with a temporary workaround. You should now be able to run the application.

Can you tell me your operation system and does your current user have administrator rights?

**Comment by Crypto-2018** [comment]
Hi,
windows 10 64, and yes

thanks
