### ISSUE TITLE
Its stop working (((

### ISSUE THREAD

**Issue by Missgoodluck** [MarcDrexler/3Commas.BulkEditor#17]
Its working good, and today  its now not upload the App,  ihave win 7 64  and enable TLS 1.2 2 weeks ago and everything was ok.
What could happen (((

//
15.11.2020 15:35:35 Information: Retrieving bots from 3Commas... 15.11.2020 15:35:37 Error: An error occurred: 3Commas Issue Connection: Error getting response from server: System.Net.Http.HttpRequestException: There was an error in sending the request.---.Net.WebException: The request was interrupted: SSL/TLS could not be created.at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) at System.Net.http.Http.HttpClientHandler.GetResponseCallback (IAsyncResult ar) --- End of tracing of internal exclusion stack --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot (Task task) at XCommas.Net.XCommasApi. <GetRawResponse>d__106.MoveNext()

**Comment by Missgoodluck** [comment]
@MarcDrexler  Maybe  you made the new update this time and my version stop  working ((( can you please fix it or can i have the previous version thats work good ((((
p/s may be //ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;    // and it will help to fix it ((i dont know you know better (((

**Comment by MarcDrexler** [comment]
@Missgoodluck 
I have uploaded the previous version [here](https://marcdrexler.blob.core.windows.net/bulkeditor/BulkEditor%201.17.0.0.zip)
Give it a try and let me know if it helped. But I don't think it was the update.

**Comment by Missgoodluck** [comment]
@MarcDrexler oh No, its the same problem(( why its stop working ((( it was good and long and shorts ((( what could happen (((

**Comment by Missgoodluck** [comment]
Thank you @MarcDrexler  for your help everything start working amazing !
