### ISSUE TITLE
Woulb be great to work with compiste bots

### ISSUE THREAD

**Issue by rocko2** [MarcDrexler/3Commas.BulkEditor#20]

**Comment by faustogut** [comment]
I agree.
What does it take to be done?
Maybe I can help you with that.
Thank you. Awesome work.

**Comment by MarcDrexler** [comment]
I have just published a new release (v1.23) and you should be able to edit+copy+delete composite bots.

**Comment by rocko2** [comment]
Wow! It works awesomely! :-)
You are great!
BR
