### ISSUE TITLE
Grid bots support sometime?

### ISSUE THREAD

**Issue by adpATza** [MarcDrexler/3Commas.BulkEditor#21]
HI Mark, thanks for this tool.  Do you perhaps plan to add support for grid bots at some point, perhaps in a separate tab?

**Comment by MarcDrexler** [comment]
At the moment I don't have a suitable subscription to play around with grid bots and I don't want to upgrade for something I am not using. Currently I only use some DCA bots for myself. So there is no plan today, but maybe at a later time.

**Comment by MarcDrexler** [comment]
I have just added grid bots in a new tab.
