### ISSUE TITLE
Ability to edit pair would be great

### ISSUE THREAD

**Issue by adpATza** [MarcDrexler/3Commas.BulkEditor#22]
Hi Mark, I'm not sure if perhaps I'm using the editor incorrectly, but although the pair seems editable it doesn't make any changes to the pair back on 3Commas.  Is it possible to add support/ability to edit the pair via your editor?

**Comment by MarcDrexler** [comment]
Hi!
I guess you changed the values ​​directly in the cells. This is not the way how it works and I have to disable that.
You can only edit values by clicking on "Edit" and make your changes in the popup window.

Edit a pair is not yet supported. There is already an issue open for that: #15

**Comment by MarcDrexler** [comment]
This feature has been added. You can now edit the pair.
