### ISSUE TITLE
profit currency edit

### ISSUE THREAD

**Issue by almokri** [MarcDrexler/3Commas.BulkEditor#23]
Dear Mark
I trust you are well.
Still waiting for option for editing profit currency in 3c BOTS.
Thank you very much.
Wish you the best.
Dr.A.Mokri

**Comment by MarcDrexler** [comment]
Hi,
it should be possible now.
Let me know if it works for you.

**Comment by almokri** [comment]
Hi.
Thanks for providing brand new options which are wonderful in Bulk Editor.
My concern was about editing profit currency which means For example in
BNB_BTC pair ,instead of taking profit in BTC the bot takes profit in BNB.
Kind regards,
Dr.A..Mokri
