### ISSUE TITLE
Profit Ratio

### ISSUE THREAD

**Issue by takizz** [MarcDrexler/3Commas.BulkEditor#24]
Hello Marc! Glad that i came up with this fantastic tool. What about an extra section/column to devide the FinishedDealsProfit USD / FinishedDealsCount to get the profit ratio per pair  ?

Cheers.

**Comment by MarcDrexler** [comment]
Hi! Yes why not. That's a little thing I can add in between.

**Comment by MarcDrexler** [comment]
@takizz 
Just created a new version with the new column.

**Comment by takizz** [comment]
Thats great! Thanks a lot, very useful
