### ISSUE TITLE
Stop orders

### ISSUE THREAD

**Issue by Trivo2311** [MarcDrexler/3Commas.BulkEditor#26]
Could you add a column to enable or disable Stop orders
Thanks Grant

**Comment by MarcDrexler** [comment]
Hi Grant,

are you talking about this option to toggle stop loss on and off?
![image](https://user-images.githubusercontent.com/16029585/107265329-6cc37000-6a44-11eb-8ebd-4793c9776a80.png)

Unfortunately the 3commas API has no parameters for this.
The only way to turn it off is to set the percentage to 0.0
Their website does the same thing when you turn it off.

Hope that helps
Marc

**Comment by Trivo2311** [comment]
Yes that is the one 
Thanks for trying, enjoy your coffees love the program
Thanks Grant

**Comment by MarcDrexler** [comment]
Thanks!! 😄
