### ISSUE TITLE
Привет. Не подключается к 3commas. Как решить ошибку эту?

### ISSUE THREAD

**Issue by ketlller** [MarcDrexler/3Commas.BulkEditor#28]
Не подключается к 3commas. Как решить ошибку эту?
Windows 7 (64)

18.02.2021 2:17:59 Information: Retrieving bots from 3Commas...
18.02.2021 2:17:59 Error: An error occurred: 3Commas Connection Issue: Error getting response from server: System.Net.Http.HttpRequestException: Произошла ошибка при отправке запроса. ---> System.Net.WebException: Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в XCommas.Net.XCommasApi.<GetRawResponse>d__106.MoveNext()

**Comment by MarcDrexler** [comment]
Duplicate 
#12
