### ISSUE TITLE
Error: Could not copy Bot, Could not update Bot

### ISSUE THREAD

**Issue by ketlller** [MarcDrexler/3Commas.BulkEditor#33]
Hi,

Once it turned out to copy the bot to another account, and then errors started:
 Could not copy Bot and Could not update Bot (Bots parameters do not change),
and in Deals, the parameters change everything is fine.

21.02.2021 13:36:22 Error: Could not copy Bot 2537813. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 13:36:25 Information: Refreshing Bots
21.02.2021 13:36:25 Information: Retrieving bots from 3Commas...
21.02.2021 13:36:28 Information: 66 bots found.
21.02.2021 13:36:53 Error: Could not update Bot 2537813. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 13:36:59 Information: Refreshing Bots
21.02.2021 13:36:59 Information: Retrieving bots from 3Commas...
21.02.2021 13:37:02 Information: 66 bots found.
21.02.2021 13:43:30 Information: Retrieving exchange information from 3Commas...
21.02.2021 13:43:30 Information: 14 Exchanges found
21.02.2021 13:43:42 Error: Could not copy Bot 2537851. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 13:43:45 Information: Refreshing Bots
21.02.2021 13:43:45 Information: Retrieving bots from 3Commas...
21.02.2021 13:43:51 Information: 66 bots found.

Thank you!

**Comment by MarcDrexler** [comment]
Hi!
have you upgraded a Simple or Composite bot? And what parameters did you set?

**Comment by ketlller** [comment]
Bots: Simple, TTP.

21.02.2021 16:32:49 Error: Could not copy Bot 2538613. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 16:32:50 Error: Could not copy Bot 2538612. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 16:32:50 Error: Could not copy Bot 2538108. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 16:32:51 Error: Could not copy Bot 2538107. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 16:32:52 Error: Could not copy Bot 2537916. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 16:32:52 Error: Could not copy Bot 2537912. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 16:32:53 Error: Could not copy Bot 2537852. Reason: signature_invalid - Provided signature is invalid -  
21.02.2021 16:32:53 Error: Could not copy Bot 2537851. Reason: signature_invalid - Provided signature is invalid -

**Comment by MarcDrexler** [comment]
hmm unfortunately I can not reproduce the behavior.
I tried to copy simple and composite bots. Editing of TTP Deviation or switching it on and off also worked.

So this error occurred after copying a bot to another account for the first time?
And now you can only look at your bots, but this error occurs with ANY modification?
Are you still seeing this problem after restarting the application?

**Comment by ketlller** [comment]
I connected three Binance accounts to 3commas. Yes, there is a problem in copying from certain accounts, and the problem is in changing the parameters in the "Bots", but everything changes well in "Deals". 

Well thank you.!
 .
