### ISSUE TITLE
Deal start condition

### ISSUE THREAD

**Issue by rontorrico** [MarcDrexler/3Commas.BulkEditor#37]
When editing the deal start condition, the non-stop condition is added automatically.

**Comment by MarcDrexler** [comment]
Duplicate of #35

**Comment by MarcDrexler** [comment]
This bug has just been fixed in the current version. Thanks for reporting! 👍

**Comment by rontorrico** [comment]
Yourre welcome! Keep up the good work 👍

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Marc <notifications@github.com>
Verzonden: Tuesday, March 2, 2021 11:18:56 PM
Aan: MarcDrexler/3Commas.BulkEditor <3Commas.BulkEditor@noreply.github.com>
CC: Author <author@noreply.github.com>
Onderwerp: Re: [MarcDrexler/3Commas.BulkEditor] Deal start condition (#37)


This bug has just been fixed in the current version. Thanks for reporting! 👍
