### ISSUE TITLE
Add more than 1 API keys to edit multiple 3c accounts

### ISSUE THREAD

**Issue by sirjimjones** [MarcDrexler/3Commas.BulkEditor#39]
Hi,

thanks for the amazing tool, Marc! It's a big help when dealing with future bots since we cannot create composite bots on 3c or 3commas.

I am running a main account on 3c and I am running a second 3c account with a smaller wallet size for testing new strategies.

It would be so nice to add multiple API credentials to manage multiple accounts with your tool! Very nice bonus would also be to copy bots between accounts! Yay!

Best regards
Jim

**Comment by MarcDrexler** [comment]
Hi Jim,

i will put it on the list. thanks for the great idea!

**Comment by MarcDrexler** [comment]
Hi Jim,
I have just added the possibility to add multiple 3commas accounts.
You can also copy bots between different 3commas accounts. Let me know if it works for you.

**Comment by sirjimjones** [comment]
Hey Marc,

thanks a ton! I am gonna check it out when I am back home!
Greatly appreciated :)

Best regards
Jim

**Comment by sirjimjones** [comment]
@MarcDrexler It's working great. That's a big enhancement :)
