### ISSUE TITLE
only long bot is display. short are missing.

### ISSUE THREAD

**Issue by MarcDrexler** [MarcDrexler/3Commas.BulkEditor#4]
i notice only long bot is display. short are missing.
btw thanks for the editor its help a lot

_Originally posted by @Biswajit96 in https://github.com/MarcDrexler/3Commas.BulkEditor/issues/1#issuecomment-696829246_

**Comment by MarcDrexler** [comment]
@Biswajit96
I cannot reproduce your issue:

![image](https://user-images.githubusercontent.com/16029585/94206250-494cbe00-fec5-11ea-9f2c-37b1f51c91f7.png)

Maybe there is still an active filter after you've updated your bots?

**Comment by Mkopl360** [comment]
It’s work perfectly
