### ISSUE TITLE
Cant change bot settings, as the window is too big - buttons to save/execute settings not visible

### ISSUE THREAD

**Issue by SJ8910** [MarcDrexler/3Commas.BulkEditor#41]
![bulk_edit_buttons_not_visible](https://user-images.githubusercontent.com/80316921/110443644-6e706a00-80bc-11eb-822a-73ec41b60b23.PNG)

**Comment by MarcDrexler** [comment]
Fixed in v1.25.

The window is now resizable and a scrollbar has been added.

Thanks for the bug report!
