### ISSUE TITLE
Profit currency editing

### ISSUE THREAD

**Issue by almokri** [MarcDrexler/3Commas.BulkEditor#44]
Hi.
Thanks for providing brand new options which are wonderful in Bulk Editor.
My concern was about editing profit currency which means For example in BNB_BTC pair ,instead of taking profit in BTC the bot takes profit in BNB.
Kind regards,
Dr.A..Mokri

**Comment by MarcDrexler** [comment]
Hi,
ok now I understand which Profit currency you are talking about:
![image](https://user-images.githubusercontent.com/16029585/111272821-61f78e80-8633-11eb-8f46-690f36f37174.png)
I will add that field later today.

**Comment by MarcDrexler** [comment]
The new field has been added:

![image](https://user-images.githubusercontent.com/16029585/111376592-ed0e6e00-869f-11eb-8362-7e840fe94470.png)

**Comment by almokri** [comment]
😊😊😊😊😊😊🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻
