### ISSUE TITLE
Does it also work if I am running few bots on the FTX.COM Exchange?

### ISSUE THREAD

**Issue by samir-jdi** [MarcDrexler/3Commas.BulkEditor#46]
Does it also work if I am running few bots on the FTX.COM Exchange?

**Comment by MarcDrexler** [comment]
Yes this should work. The program doesn't care about the exchange linked with your bots.

**Comment by samir-jdi** [comment]
Thank you, just asking because this is what you stated at the end of your post:

![image](https://user-images.githubusercontent.com/41586535/111909665-27ca2a80-8a41-11eb-95bd-22dbf445bbe7.png)

**Comment by MarcDrexler** [comment]
haha no. I just thought it was a good way to place some ref links 😄 
I will close your question and you can try it out.
Let me know if you have any problems with this.
