### ISSUE TITLE
Request: Bulk Copy bots

### ISSUE THREAD

**Issue by Mkopl360** [MarcDrexler/3Commas.BulkEditor#6]
Its possible to add bulk copy bot from one exchange account to other exchange account in same 3commas account?
anyone help please.
and thanks for all previous developments. 🥇

**Comment by Mkopl360** [comment]
sir possible to do paid custom development ?

**Comment by MarcDrexler** [comment]
Hi!
It is not the actual use case of the bulk editor, but I'll see how I can integrate this feature.

**Comment by Mkopl360** [comment]
thank you so much , it will help a lot with future trading. because can't run multiple singles in same account. (i mean we can but its create problems) waiting for your update.... <3

**Comment by MarcDrexler** [comment]
@Biswajit96 Is there a way to contact you directly? I could give you a pre-release version to test if you want.

**Comment by Biswajit96** [comment]
sir, my mail : bisu758@gmail.com
skype : b.das_
please share me when ever you want.

**Comment by Biswajit96** [comment]
sir,
i have try to mail you but its was not deliver.
my telegram : bisu7589

**Comment by MarcDrexler** [comment]
This feature has just been added 🥳
