### ISSUE TITLE
Fix the text of switching between accounts confirmation

### ISSUE THREAD

**Issue by hosseinpourakbar** [MarcDrexler/3Commas.BulkEditor#60]
Hello @MarcDrexler 

Here is a suggestion:
When you want to switch from real account to paper account, it displays a confirmation box. In this box, it always asks if you want to switch from paper to real, while I would like to do the reverse. You can change the text to a proper one since it is a bit confusing.

Thanks in advance,
Hossein POURAKBAR

**Comment by MarcDrexler** [comment]
Thanks for the tip Hossein.
It has been fixed in the latest version of BotManager.
