### ISSUE TITLE
Unable to add QFL deal start (Position, 3%)

### ISSUE THREAD

**Issue by quantatrading** [MarcDrexler/3Commas.BulkEditor#8]
Hi,

Trying to bulk edit a custom deal start using QFL. BulkEditor only provides a custom option of QFL however its missing 2 parameters (see attached).

![image](https://user-images.githubusercontent.com/3750100/96717478-71352180-139e-11eb-95ac-a9018872115b.png)

Is it possible to add QFL as a selection type please?

**Comment by MarcDrexler** [comment]
Hi!
This type of selection wasn't implemented yet and I just added it.
Let me know if it works for you.

**Comment by quantatrading** [comment]
Just tested, works perfectly. Super quick turnaround - thank you
