### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by Trivo2311** [MarcDrexler/3Commas.BulkEditor#9]
Hi 3Commas.BulkEditor creator
I have tried to add 4 different API keys and they all get a warning 
30/10/2020 7:04:05 AM Information: Retrieving bots from 3Commas...
30/10/2020 7:04:06 AM Error: An error occurred: 3Commas Connection Issue: api_key_invalid_or_expired - Unauthorized. Invalid or expired api key. -  
I have all permissions set on
Thanks for your help
Grant

**Comment by MarcDrexler** [comment]
Hi!

I tried to reproduce your issue somehow, but I couldn't...

- I created new API Keys for myself, to rule out that there is recently a difference between old and new API Keys. But those work on my side.
- Then I added blanks before and after the text (sometimes there might be a blank if copy & pasted), but in that case another error would occur. So it is something else..

I believe, that you have already double checked the API Key and Secret, but there must be something wrong with one of them... 
Are API Key and Secret turned around maybe? Then it would result in the same error message that has been returned from 3commas to you.

**Comment by Trivo2311** [comment]
Just checking that I should be using the API keys from Binance, and FTX exchanges and there is not an API for 3commas?
I have 1 main account and several Sub Accounts, spot and futures and I have made new one today but all have the same result 

I might try another computer tomorrow

Thank you for getting back to me
Grant

**Comment by MarcDrexler** [comment]
That API Key has nothing to do with your exchange account (binance in your case) or any sub-account on there...
This tool only talks with 3commas, not with your exchange.

So you need to provide the API Key of 3commas API:

![image](https://user-images.githubusercontent.com/16029585/97704443-adf5cc80-1ab2-11eb-974d-47307bc6bb22.png)

Those permissions are needed:

![image](https://user-images.githubusercontent.com/16029585/97704855-6d4a8300-1ab3-11eb-9b64-4cdee6646e29.png)

**Comment by Trivo2311** [comment]
That works perfectly thank you
